#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wmake combustion/catalyticZonesReactingFoam

wmake libso combustion/catalyticWallsReactingFoam/derivedFvPatchFields
wmake combustion/catalyticWallsReactingFoam

multiphase/multiphaseEulerFoam/Allwmake

#------------------------------------------------------------------------------
