#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean combustion/catalyticZonesReactingFoam

wclean combustion/catalyticWallsReactingFoam/derivedFvPatchFields
wclean combustion/catalyticWallsReactingFoam

multiphase/multiphaseEulerFoam/Allwclean

#------------------------------------------------------------------------------
