#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean
find . -maxdepth 1 -mindepth 1 -type d  ! -name Make ! -name rhoReactionThermo -exec rm -r {} \;

wclean rhoReactionThermo
find rhoReactionThermo -mindepth 1 -maxdepth 1 -type d  ! -name Make -exec rm -r {} \;
rm -f rhoReactionThermo/rhoReactionThermo*.*

#------------------------------------------------------------------------------
