#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Clean catchyFOAM libraries
src/Allwclean

# Clean catchyFOAM solvers
applications/solvers/Allwclean

# Clean catchyFOAM utilities
applications/utilities/Allwclean

#------------------------------------------------------------------------------
