#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0
rm -f constant/mechanism/*.gas
rm -f constant/mechanism/*.surf
rm -f system/fvSolution system/controlDict system/decomposeParDict
cleanCase

#------------------------------------------------------------------------------
