#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ -x "$(command -v canteraToFoam)" ]; then
    runApplication canteraToFoam constant/mechanism/rhAl2O3.cti gas constant/mechanism/transportProperties constant/mechanism/chem constant/mechanism/thermo -surface Rh_surface -transport
else
    echo "canteraToFoam not available - copying input files from backup"
    cp $CATCHY_ETC/backupDicts/mechanisms/rhAl2O3/* constant/mechanism/
fi

cp -r 0.org 0
runApplication blockMesh
runApplication $(getApplication)

runApplication -s post $(getApplication) -postProcess -func moleFractions -latestTime
runApplication -s componentsU postProcess -func 'components(U)' -latestTime
runApplication -s sample postProcess -func sampleMass -latestTime
runApplication -s sampleW postProcess -func sampleWall -latestTime

#------------------------------------------------------------------------------
