#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -rf combustionModel
rm -rf CombustionModel
rm -rf laminar
rm -rf noCombustion
rm -rf functionObjects

wclean

#------------------------------------------------------------------------------
