#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

cp -rn $WM_PROJECT_DIR/src/combustionModels/combustionModel .
cp -rn $WM_PROJECT_DIR/src/combustionModels/CombustionModel .
cp -rn $WM_PROJECT_DIR/src/combustionModels/laminar .
cp -rn $WM_PROJECT_DIR/src/combustionModels/noCombustion .
cp -rn $WM_PROJECT_DIR/src/combustionModels/functionObjects .

wmake libso

#------------------------------------------------------------------------------
