#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake libso phaseSystems
wmake libso interfacialModels
wmake libso interfacialCompositionModels
wmake libso multiphaseCompressibleMomentumTransportModels
wmake libso multiphaseThermophysicalTransportModels
multiphaseEulerFoam/Allwmake
wmake libso functionObjects

#------------------------------------------------------------------------------
