#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

thermophysicalModels/Allwclean
MomentumTransportModels/compressible/Allwclean
ThermophysicalTransportModels/Allwclean
combustionModels/Allwclean
fvOptions/Allwclean
functionObjects/Allwclean
specieTransfer/Allwclean

#------------------------------------------------------------------------------
