#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ -x "$(command -v canteraToFoam)" ]; then
    runApplication canteraToFoam constant/mechanism/ocm_lct_srla2o3.cti gas constant/mechanism/transportProperties constant/mechanism/chem constant/mechanism/thermo -surface surface1 -transport
else
    echo "canteraToFoam not available - copying input files from backup"
    cp $CATCHY_ETC/backupDicts/mechanisms/ocm_lct_srla2o3/* constant/mechanism/
fi

cp -r 0.org 0
runApplication blockMesh
runApplication topoSet
runApplication $(getApplication)

runApplication postProcess -func sample -latestTime

#------------------------------------------------------------------------------
